version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Starting SAM packaging..."
      - sam package --output-template-file packaged.yaml --s3-bucket full-stack-app-imagebucket-gz8rufxy6coo
artifacts:
  files:
    - packaged.yaml
